export const PRODUCT_LIST_REQUEST = "PRODUCT_LIST_REQUEST";
export const PRODUCT_LIST_SUCCESS = "PRODUCT_LIST_SUCCESS";
export const PRODUCT_LIST_FAILS = "PRODUCT_LIST_FAILS";

export const PRODUCT_ADD_REQUEST = "PRODUCT_ADD_REQUEST";
export const PRODUCT_ADD_SUCCESS = "PRODUCT_ADD_SUCCESS";
export const PRODUCT_ADD_FAILS = "PRODUCT_ADD_FAILS";

export const PRODUCT_UPDATE_REQUEST = "PRODUCT_UPDATE_REQUEST";
export const PRODUCT_UPDATE_SUCCESS = "PRODUCT_UPDATE_SUCCESS";
export const PRODUCT_UPDATE_FAILS = "PRODUCT_UPDATE_FAILS";

export const PRODUCT_GET_REQUEST = "PRODUCT_GET_REQUEST";
export const PRODUCT_GET_SUCCESS = "PRODUCT_GET_SUCCESS";
export const PRODUCT_GET_FAILS = "PRODUCT_GET_FAILS";

export const PRODUCT_SELLER_REQUEST = "PRODUCT_SELLER_REQUEST";
export const PRODUCT_SELLER_SUCCESS = "PRODUCT_SELLER_SUCCESS";
export const PRODUCT_SELLER_FAILS = "PRODUCT_SELLER_FAILS";

export const GET_PRODUCTBYID_REQUEST = "GET_PRODUCTBYID_REQUEST";
export const GET_PRODUCTBYID_SUCCESS = "GET_PRODUCTBYID_SUCCESS";
export const GET_PRODUCTBYID_FAILS = "GET_PRODUCTBYID_FAILS";

export const UPDATE_PRODUCTBYID_REQUEST = "UPDATE_PRODUCTBYID_REQUEST";
export const UPDATE_PRODUCTBYID_SUCCESS = "UPDATE_PRODUCTBYID_SUCCESS";
export const UPDATE_PRODUCTBYID_FAILS = "UPDATE_PRODUCTBYID_FAILS";

export const PRODUCT_CREATE_REVIEW_REQUEST = "PRODUCT_CREATE_REVIEW_REQUEST";
export const PRODUCT_CREATE_REVIEW_SUCCESS = "PRODUCT_CREATE_REVIEW_SUCCESS";
export const PRODUCT_CREATE_REVIEW_FAIL = "PRODUCT_CREATE_REVIEW_FAIL";
export const PRODUCT_CREATE_REVIEW_RESET = "PRODUCT_CREATE_REVIEW_RESET";

export const PRODUCT_REVIEW_LIST_REQUEST = "PRODUCT_REVIEW_LIST_REQUEST";
export const PRODUCT_REVIEW_LIST_SUCCESS = "PRODUCT_REVIEW_LIST_SUCCESS";
export const PRODUCT_REVIEW_LIST_FAILS = "PRODUCT_REVIEW_LIST_FAILS";

export const PRODUCT_CREATE_REVIEW2_REQUEST = "PRODUCT_CREATE_REVIEW2_REQUEST";
export const PRODUCT_CREATE_REVIEW2_SUCCESS = "PRODUCT_CREATE_REVIEW2_SUCCESS";
export const PRODUCT_CREATE_REVIEW2_FAIL = "PRODUCT_CREATE_REVIEW2_FAIL";
export const PRODUCT_CREATE_REVIEW2_RESET = "PRODUCT_CREATE_REVIEW2_RESET";

export const PRODUCT_LIST1_REQUEST = "PRODUCT_LIST1_REQUEST";
export const PRODUCT_LIST1_SUCCESS = "PRODUCT_LIST1_SUCCESS";
export const PRODUCT_LIST1_FAILS = "PRODUCT_LIST1_FAILS";

export const PRODUCT_TRY_REQUEST = "PRODUCT_TRY_REQUEST";
export const PRODUCT_TRY_SUCCESS = "PRODUCT_TRY_SUCCESS";
export const PRODUCT_TRY_FAILS = "PRODUCT_TRY_FAILS";

export const PRODUCT_TRY1_REQUEST = "PRODUCT_TRY1_REQUEST";
export const PRODUCT_TRY1_SUCCESS = "PRODUCT_TRY1_SUCCESS";
export const PRODUCT_TRY1_FAILS = "PRODUCT_TRY1_FAILS";
